<?xml version="1.0" encoding="utf-8"?><Database Name="FrankHogan_Warranty" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\FrankHogan_Warranty.mdf;Integrated Security=True" SettingsObjectName="FrankHogan_WarrantySystem.Properties.Settings" SettingsPropertyName="FrankHogan_WarrantyConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cars" Member="Cars">
    <Type Name="Car">
      <Column Name="VIN" Type="System.String" DbType="Char(17) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Make_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Mileage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Car_Repair" Member="Repairs" ThisKey="VIN" OtherKey="VIN" Type="Repair" />
      <Association Name="Make_Car" Member="Make" ThisKey="Make_ID" OtherKey="Make_ID" Type="Make" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Claims" Member="Claims">
    <Type Name="Claim">
      <Column Name="Claim_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClaimNumber" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="ClaimType_ID" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="Repair_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaimDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TimeAllowed" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Status_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ManuCode" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="ClaimType_Claim" Member="ClaimType" ThisKey="ClaimType_ID" OtherKey="ClaimType_ID" Type="ClaimType" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Repair_Claim" Member="Repair" ThisKey="Repair_ID" OtherKey="Repair_ID" Type="Repair" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Status_Claim" Member="Status" ThisKey="Status_ID" OtherKey="Status_ID" Type="Status" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.ClaimTypes" Member="ClaimTypes">
    <Type Name="ClaimType">
      <Column Name="ClaimType_ID" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TypeDescription" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Association Name="ClaimType_Claim" Member="Claims" ThisKey="ClaimType_ID" OtherKey="ClaimType_ID" Type="Claim" />
    </Type>
  </Table>
  <Table Name="dbo.Faults" Member="Faults">
    <Type Name="Fault">
      <Column Name="Fault_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fault" Member="Fault1" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Group_ID" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Association Name="Fault_Repair" Member="Repairs" ThisKey="Fault_ID" OtherKey="Fault_ID" Type="Repair" />
      <Association Name="Group_Fault" Member="Group" ThisKey="Group_ID" OtherKey="Group_ID" Type="Group" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Group">
      <Column Name="Group_ID" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupDescription" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Association Name="Group_Fault" Member="Faults" ThisKey="Group_ID" OtherKey="Group_ID" Type="Fault" />
    </Type>
  </Table>
  <Table Name="dbo.LabourRates" Member="LabourRates">
    <Type Name="LabourRate">
      <Column Name="LabourRate_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="LabourRate_Make" Member="Makes" ThisKey="LabourRate_ID" OtherKey="WAR_LRate_ID" Type="Make" />
    </Type>
  </Table>
  <Table Name="dbo.Makes" Member="Makes">
    <Type Name="Make">
      <Column Name="Make_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="WAR_LRate_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SER_LRate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Make_Car" Member="Cars" ThisKey="Make_ID" OtherKey="Make_ID" Type="Car" />
      <Association Name="LabourRate_Make" Member="LabourRate" ThisKey="WAR_LRate_ID" OtherKey="LabourRate_ID" Type="LabourRate" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Repairs" Member="Repairs">
    <Type Name="Repair">
      <Column Name="Repair_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RepairOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VIN" Type="System.String" DbType="Char(17) NOT NULL" CanBeNull="false" />
      <Column Name="Fault_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Solution_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceptionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="RepairDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TimeTaken" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Repair_Claim" Member="Claims" ThisKey="Repair_ID" OtherKey="Repair_ID" Type="Claim" />
      <Association Name="Fault_Repair" Member="Fault" ThisKey="Fault_ID" OtherKey="Fault_ID" Type="Fault" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Car_Repair" Member="Car" ThisKey="VIN" OtherKey="VIN" Type="Car" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Solution_Repair" Member="Solution" ThisKey="Solution_ID" OtherKey="Solution_ID" Type="Solution" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Solutions" Member="Solutions">
    <Type Name="Solution">
      <Column Name="Solution_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Solution" Member="Solution1" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Association Name="Solution_Repair" Member="Repairs" ThisKey="Solution_ID" OtherKey="Solution_ID" Type="Repair" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="Status_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Status_Claim" Member="Claims" ThisKey="Status_ID" OtherKey="Status_ID" Type="Claim" />
    </Type>
  </Table>
  <Function Name="dbo.sp11FaultInsertion" Method="sp11FaultInsertion">
    <Parameter Name="FaultText" Parameter="faultText" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="Group" Parameter="group" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp12RepairInsertion" Method="sp12RepairInsertion">
    <Parameter Name="RepairOrder" Parameter="repairOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <Parameter Name="Fault" Parameter="fault" Type="System.Int32" DbType="Int" />
    <Parameter Name="Solution" Parameter="solution" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReceptionDate" Parameter="receptionDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="RepairDate" Parameter="repairDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TimeTaken" Parameter="timeTaken" Type="System.Double" DbType="Float" />
    <Parameter Name="Invoice" Parameter="invoice" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp13ClaimInsertion" Method="sp13ClaimInsertion">
    <Parameter Name="ClaimNumber" Parameter="claimNumber" Type="System.String" DbType="Char(8)" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="Char(4)" />
    <Parameter Name="Repair" Parameter="repair" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ClaimValue" Parameter="claimValue" Type="System.Decimal" DbType="Money" />
    <Parameter Name="TimeAllowed" Parameter="timeAllowed" Type="System.Double" DbType="Float" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="PaymentDate" Parameter="paymentDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ManufacturerCode" Parameter="manufacturerCode" Type="System.String" DbType="Char(3)" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp14UpdateStatus" Method="sp14UpdateStatus">
    <Parameter Name="Claim" Parameter="claim" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp15UpdateClaimValue" Method="sp15UpdateClaimValue">
    <Parameter Name="Claim" Parameter="claim" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp16UpdateTimeAllowed" Method="sp16UpdateTimeAllowed">
    <Parameter Name="Claim" Parameter="claim" Type="System.Int32" DbType="Int" />
    <Parameter Name="Time" Parameter="time" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp18SolutionInsertion" Method="sp18SolutionInsertion">
    <Parameter Name="SolutionText" Parameter="solutionText" Type="System.String" DbType="VarChar(60)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp3CalculateWSPerformance" Method="sp3CalculateWSPerformance">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Make" Parameter="make" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Performance" Parameter="performance" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp7CarDetailsByVIN" Method="sp7CarDetailsByVIN">
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <ElementType Name="sp7CarDetailsByVINResult">
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="RegNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Mileage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp4ListOfClaimsByVIN" Method="sp4ListOfClaimsByVIN">
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <ElementType Name="sp4ListOfClaimsByVINResult">
      <Column Name="ClaimNumber" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="ClaimType_ID" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="VIN" Type="System.String" DbType="Char(17) NOT NULL" CanBeNull="false" />
      <Column Name="[Registration number]" Member="Registration_number" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Repair" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="[Claim Value]" Member="Claim_Value" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="[Claim Date]" Member="Claim_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp15UpdateClaimValue" Method="sp15UpdateClaimValue1">
    <Parameter Name="Claim" Parameter="claim" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp16UpdateTimeAllowed" Method="sp16UpdateTimeAllowed1">
    <Parameter Name="Claim" Parameter="claim" Type="System.Int32" DbType="Int" />
    <Parameter Name="Time" Parameter="time" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp11FaultInsertion" Method="sp11FaultInsertion1">
    <Parameter Name="FaultText" Parameter="faultText" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="Group" Parameter="group" Type="System.String" DbType="Char(2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp12RepairInsertion" Method="sp12RepairInsertion1">
    <Parameter Name="RepairOrder" Parameter="repairOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <Parameter Name="Fault" Parameter="fault" Type="System.Int32" DbType="Int" />
    <Parameter Name="Solution" Parameter="solution" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReceptionDate" Parameter="receptionDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="RepairDate" Parameter="repairDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TimeTaken" Parameter="timeTaken" Type="System.Double" DbType="Float" />
    <Parameter Name="Invoice" Parameter="invoice" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp6GetInvoiceNumber" Method="sp6GetInvoiceNumber">
    <Parameter Name="ClaimNumber" Parameter="claimNumber" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <Parameter Name="Invoice" Parameter="invoice" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp9ClaimDetails" Method="sp9ClaimDetails">
    <Parameter Name="Claim" Parameter="claim" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <ElementType Name="sp9ClaimDetailsResult">
      <Column Name="ClaimType_ID" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="TypeDescription" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TimeAllowed" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ManuCode" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RepairOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceptionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="RepairDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TimeTaken" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mileage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Fault" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Solution" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Group_ID" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="GroupDescription" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp24UpdateRepair" Method="sp24UpdateRepair">
    <Parameter Name="RepairID" Parameter="repairID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RepairOrder" Parameter="repairOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <Parameter Name="Fault" Parameter="fault" Type="System.Int32" DbType="Int" />
    <Parameter Name="Solution" Parameter="solution" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReceptionDate" Parameter="receptionDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="RepairDate" Parameter="repairDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TimeTaken" Parameter="timeTaken" Type="System.Double" DbType="Float" />
    <Parameter Name="Invoice" Parameter="invoice" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp27DeleteClaim" Method="sp27DeleteClaim">
    <Parameter Name="ClaimNumber" Parameter="claimNumber" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp5ListOfClaimsByReg" Method="sp5ListOfClaimsByReg">
    <Parameter Name="Reg" Parameter="reg" Type="System.String" DbType="VarChar(12)" />
    <ElementType Name="sp5ListOfClaimsByRegResult">
      <Column Name="ClaimNumber" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType_ID" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="VIN" Type="System.String" DbType="Char(17) NOT NULL" CanBeNull="false" />
      <Column Name="[Registration number]" Member="Registration_number" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Repair" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="[Claim Value]" Member="Claim_Value" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="[Claim Date]" Member="Claim_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp8CarDetailsByReg" Method="sp8CarDetailsByReg">
    <Parameter Name="Reg" Parameter="reg" Type="System.String" DbType="VarChar(12)" />
    <ElementType Name="sp8CarDetailsByRegResult">
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="VIN" Type="System.String" DbType="Char(17) NOT NULL" CanBeNull="false" />
      <Column Name="Mileage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp10CarInsertion" Method="sp10CarInsertion">
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <Parameter Name="Make" Parameter="make" Type="System.Int32" DbType="Int" />
    <Parameter Name="RegNumber" Parameter="regNumber" Type="System.String" DbType="VarChar(12)" />
    <Parameter Name="Mileage" Parameter="mileage" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp22UpdateRegNumber" Method="sp22UpdateRegNumber">
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <Parameter Name="RegNumber" Parameter="regNumber" Type="System.String" DbType="VarChar(12)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp23UpdateCar" Method="sp23UpdateCar">
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <Parameter Name="Make" Parameter="make" Type="System.Int32" DbType="Int" />
    <Parameter Name="RegNumber" Parameter="regNumber" Type="System.String" DbType="VarChar(12)" />
    <Parameter Name="Mileage" Parameter="mileage" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp25UpdateClaim" Method="sp25UpdateClaim">
    <Parameter Name="ClaimID" Parameter="claimID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClaimNumber" Parameter="claimNumber" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="Char(4)" />
    <Parameter Name="Repair" Parameter="repair" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ClaimValue" Parameter="claimValue" Type="System.Decimal" DbType="Money" />
    <Parameter Name="TimeAllowed" Parameter="timeAllowed" Type="System.Double" DbType="Float" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="PaymentDate" Parameter="paymentDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ManufacturerCode" Parameter="manufacturerCode" Type="System.String" DbType="Char(3)" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp26UpdateClaimTransaction" Method="sp26UpdateClaimTransaction">
    <Parameter Name="VIN_Insert" Parameter="vIN_Insert" Type="System.String" DbType="Char(17)" />
    <Parameter Name="Mileage_Insert" Parameter="mileage_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="Make_Insert" Parameter="make_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="RegNumber_Insert" Parameter="regNumber_Insert" Type="System.String" DbType="VarChar(12)" />
    <Parameter Name="FaultID_Insert" Parameter="faultID_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="FaultDescription" Parameter="faultDescription" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="GroupID_Insert" Parameter="groupID_Insert" Type="System.String" DbType="Char(2)" />
    <Parameter Name="SolutionID_Insert" Parameter="solutionID_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="Solution_Insert" Parameter="solution_Insert" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="RepairOrder_Insert" Parameter="repairOrder_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReceptionDate_Insert" Parameter="receptionDate_Insert" Type="System.DateTime" DbType="Date" />
    <Parameter Name="RepairDate_Insert" Parameter="repairDate_Insert" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TimeTaken_Insert" Parameter="timeTaken_Insert" Type="System.Double" DbType="Float" />
    <Parameter Name="Invoice_Insert" Parameter="invoice_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClaimNumber_Insert" Parameter="claimNumber_Insert" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="Type_Insert" Parameter="type_Insert" Type="System.String" DbType="Char(4)" />
    <Parameter Name="ClaimDate" Parameter="claimDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ClaimValue_Insert" Parameter="claimValue_Insert" Type="System.Decimal" DbType="Money" />
    <Parameter Name="TimeAllowed_Insert" Parameter="timeAllowed_Insert" Type="System.Double" DbType="Float" />
    <Parameter Name="Status_Insert" Parameter="status_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="PaymentDate_Insert" Parameter="paymentDate_Insert" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ManuCode_Insert" Parameter="manuCode_Insert" Type="System.String" DbType="Char(3)" />
    <Parameter Name="Comment_Insert" Parameter="comment_Insert" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp20FilterClaims" Method="sp20FilterClaims">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Make" Parameter="make" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Group" Parameter="group" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="MinValue" Parameter="minValue" Type="System.Decimal" DbType="Money" />
    <Parameter Name="MaxValue" Parameter="maxValue" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Fault" Parameter="fault" Type="System.String" DbType="VarChar(60)" />
    <ElementType Name="sp20FilterClaimsResult">
      <Column Name="ClaimNumber" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType_ID" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="VIN" Type="System.String" DbType="Char(17) NOT NULL" CanBeNull="false" />
      <Column Name="RegNumber" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Make" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Mileage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fault" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="RepairDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ClaimDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TimeTaken" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TimeAllowed" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="InvoiceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp19InsertClaimTransaction" Method="sp19InsertClaimTransaction">
    <Parameter Name="VIN_Insert" Parameter="vIN_Insert" Type="System.String" DbType="Char(17)" />
    <Parameter Name="Mileage_Insert" Parameter="mileage_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="Make_Insert" Parameter="make_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="RegNumber_Insert" Parameter="regNumber_Insert" Type="System.String" DbType="VarChar(12)" />
    <Parameter Name="FaultID_Insert" Parameter="faultID_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="FaultDescription" Parameter="faultDescription" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="GroupID_Insert" Parameter="groupID_Insert" Type="System.String" DbType="Char(2)" />
    <Parameter Name="SolutionID_Insert" Parameter="solutionID_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="Solution_Insert" Parameter="solution_Insert" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="RepairOrder_Insert" Parameter="repairOrder_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReceptionDate_Insert" Parameter="receptionDate_Insert" Type="System.DateTime" DbType="Date" />
    <Parameter Name="RepairDate_Insert" Parameter="repairDate_Insert" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TimeTaken_Insert" Parameter="timeTaken_Insert" Type="System.Double" DbType="Float" />
    <Parameter Name="Invoice_Insert" Parameter="invoice_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClaimNumber_Insert" Parameter="claimNumber_Insert" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="Type_Insert" Parameter="type_Insert" Type="System.String" DbType="Char(4)" />
    <Parameter Name="ClaimDate" Parameter="claimDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ClaimValue_Insert" Parameter="claimValue_Insert" Type="System.Decimal" DbType="Money" />
    <Parameter Name="TimeAllowed_Insert" Parameter="timeAllowed_Insert" Type="System.Double" DbType="Float" />
    <Parameter Name="Status_Insert" Parameter="status_Insert" Type="System.Int32" DbType="Int" />
    <Parameter Name="PaymentDate_Insert" Parameter="paymentDate_Insert" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ManuCode_Insert" Parameter="manuCode_Insert" Type="System.String" DbType="Char(3)" />
    <Parameter Name="Comment_Insert" Parameter="comment_Insert" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp17UpdateMileage" Method="sp17UpdateMileage">
    <Parameter Name="VIN" Parameter="vIN" Type="System.String" DbType="Char(17)" />
    <Parameter Name="Mileage" Parameter="mileage" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp2CalculateClaimingSpeed" Method="sp2CalculateClaimingSpeed">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Make" Parameter="make" Type="System.Int32" DbType="Int" />
    <Parameter Name="SpeedKPI" Parameter="speedKPI" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp1CountClaims" Method="sp1CountClaims">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Make" Parameter="make" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Group" Parameter="group" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="MinValue" Parameter="minValue" Type="System.Decimal" DbType="Money" />
    <Parameter Name="MaxValue" Parameter="maxValue" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Fault" Parameter="fault" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="NumberOfClaims" Parameter="numberOfClaims" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ClaimedValue" Parameter="claimedValue" Type="System.Decimal" DbType="Money" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp21LabourClaimed" Method="sp21LabourClaimed">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Make" Parameter="make" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Group" Parameter="group" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="MinValue" Parameter="minValue" Type="System.Decimal" DbType="Money" />
    <Parameter Name="MaxValue" Parameter="maxValue" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Fault" Parameter="fault" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="LabourClaimed" Parameter="labourClaimed" Type="System.Decimal" DbType="Money" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>